int a = 15;
int b = 22;
int c = 32;
int toplam = a + b + c;
Console.WriteLine(toplam);
int cıkarma = a - b - c;
Console.WriteLine(cıkarma);
int carpma = a * b * c;
Console.WriteLine(carpma);
int bolme = a / b / c;
Console.WriteLine(bolme);